#!/bin/sh

pkill -9 sxhkd; sxhkd &
pkill -9 eww; eww open bar0

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width          2
bspc config window_gap            12
bspc config top_padding           30

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# layout
bspc config automatic_scheme alternate

# colours
bspc config focused_border_color  "#d4685a"
bspc config normal_border_color   "#4a3933"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


